Repository KathFOSS-Club/kathfoss-web, pull requests merged in 2025-01, with the labels that each got.

#5 refactor: Refactored the codebase to make it simple
  CodeOfContribution.md
  FolderStructure.md
  components.json
  src/app/(root)/layout.tsx
  src/app/(routes)/events/page.tsx
  src/app/components/EventsHighlight.tsx
  src/app/components/Footer.tsx
  src/app/components/Header.tsx
  src/app/components/HeroSection.tsx
  src/app/components/HighlightedProjects.tsx
  src/app/components/ParticleAnimation/BackgroundAnimation.tsx
  src/app/components/ParticleAnimation/Particle.ts
  src/app/components/ParticleAnimation/ParticleAnimation.tsx
  src/app/components/ParticleAnimation/constants.ts
  src/app/components/ParticleAnimation/types.ts
  src/app/components/ParticleAnimation/useParticleAnimation.ts
  src/app/components/Team.tsx
  src/app/components/UpcomingEvents.tsx
  src/app/components/index.ts
  src/app/components/ui/3d-card.tsx
  src/app/events/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/common/type/type.ts
  src/config/Providers.tsx
  src/config/ThemeConfigMui.ts
  src/type/Type.ts
Labels: good first issue

#23 Updates PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#24 Fix/timer design
  public/fonts/DS-DIGIT.ttf
  src/app/components/HeroSection.tsx
  src/app/components/ui/Timer/FormatTime.tsx
  src/app/components/ui/Timer/Timer.tsx
  src/config/ThemeConfigMui.ts
  src/styles/globals.css
  src/type/Type.ts
Labels: enhancement

#30 upcoming events style enhancement
  src/app/components/UpcomingEvents.tsx
  src/app/components/ui/Timer/FormatTime.tsx
  src/app/events/page.tsx
  src/app/layout.tsx
  src/config/ThemeConfigMui.ts
Labels: enhancement

#47 Fix/meet our team
  public/images/MeetOurTeam/designer.jpg
  public/images/MeetOurTeam/designer.png
  public/images/MeetOurTeam/document-head.jpg
  public/images/MeetOurTeam/document-head.png
  public/images/MeetOurTeam/event-coordinator.jpg
  public/images/MeetOurTeam/event-coordinator.png
  public/images/MeetOurTeam/executive-member1.jpg
  public/images/MeetOurTeam/executive-member2.png
  public/images/MeetOurTeam/pr-manager.png
  public/images/MeetOurTeam/president.jpg
  public/images/MeetOurTeam/president.png
  public/images/MeetOurTeam/secretary.jpg
  public/images/MeetOurTeam/secretary.png
  public/images/MeetOurTeam/social-media-handler1.jpg
  public/images/MeetOurTeam/social-media-handler2.jpg
  public/images/MeetOurTeam/tech-lead.jpg
  public/images/MeetOurTeam/tech-lead.png
  public/images/MeetOurTeam/video-editor.jpg
  src/app/components/Header.tsx
  src/app/components/Team.tsx
  src/app/components/ui/MeetOurTeam/TeamMember.tsx
  src/app/components/ui/MeetOurTeam/TeamMemberModal.tsx
  src/app/data/meet-our-team.ts
  src/app/meet-our-team/page.tsx
  src/styles/globals.css
  src/type/team-memeber.ts
Labels: enhancement
